# Generated by Django 5.0.3 on 2024-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='img',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
