# Generated by Django 5.0.3 on 2024-09-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recept_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
