# Generated by Django 5.0.3 on 2024-09-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recept_author_alter_recept_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='img',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
