# Generated by Django 5.0.3 on 2024-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recept_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
