# Generated by Django 5.0.3 on 2024-10-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_category_alter_recept_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='watched',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
