# Generated by Django 5.0.3 on 2024-10-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_recept_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='is_published',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
